import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import MouseRadar from "@/components/MouseRadar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  variable: "--font-poppins-var",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`font-poppins antialiased flex flex-col h-screen transition-colors duration-300`}
      >
        <MouseRadar />
        <Navbar />
        <div className="flex-1 overflow-auto bg-[#eef7ff] text-black transition-colors duration-300 dark:bg-slate-950 dark:text-white">
          {children}
        </div>
      </body>
    </html>
  );
}
